
[Settings]
	#chance for special villagers (villagers with no job site block) appear in village
	specialVillagerChance = 10.0
	#disable/enable if skills of special villagers can damage iron golem or villagers
	disableDamageVillagers = true

